    platform: template
    name: ${friendly_name} ESP Internal Temp
    device_class: temperature
    unit_of_measurement: °C
    id: esp32_temp
    lambda: return temperatureRead();
    update_interval: 60s