    platform: wifi_signal
    name: ${friendly_name} ESP WiFi Signal
    id: wifi_ssid
    update_interval: 60s
    filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15