  time:
    - <<: !include ./../common/time/sntp_time.yaml
    # - <<: !include ./../common/time/ha_time.yaml  
      on_time:
      - <<: !include ./../common/time/wifi_enable_5am.yaml 
      - <<: !include ./../common/time/wifi_disable_12am.yaml 
  
  sensor:
    - <<: !include ./../common/sensor/wifi_signal.yaml
    - <<: !include ./../common/sensor/uptime.yaml
    - <<: !include ./../common/sensor/wifi_percent.yaml
  #  - <<: !include ./../common/sensor/esp32_temp.yaml
  
  binary_sensor:
    - <<: !include ./../common/binary_sensor/ha_status.yaml
  
  switch:
    #- <<: !include ./../common/switch/restart.yaml
    - <<: !include ./../common/switch/wifi_disable.yaml

  button:
    - <<: !include ./../common/button/safe_mode.yaml
    - <<: !include ./../common/button/restart.yaml

  text_sensor:
    - <<: !include ./../common/text_sensor/esphome_version.yaml
    - <<: !include ./../common/text_sensor/wifi_info.yaml