#external_components:
#  - source: github://esphome/esphome@dev
#    components:
#      - wifi

wifi:
  networks:
  - ssid: $wifi_ssid
    password: $wifi_password
  - ssid: $wifi_ssid_ha
    password: $wifi_password_ha
  reboot_timeout: 21600s #172800s
  use_address: $IP
  id: wifi_id
    # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} Fallback"
    password: $fallback_pass

captive_portal: